
name: Docker Image CI
# 触发条件：当master branch触发push（push，merge Pull Request）时，弱docker文件夹下的文件有更新，则触发。
on:
  push:
    branches:
      - master
    #paths:
     # - 'docker/**'

defaults:
  run:
    shell: bash
    working-directory: './docker'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
      - name: Push to Ali Docker Repository
        run: |
          docker login -u ${{ secrets.ALI_DOCKER_HUB_USN }} -p ${{ secrets.ALI_DOCKER_HUB_PWD }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          docker tag locale ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/username/repository:tag
          docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/username/repository:tag

