name: Docker Image CI
# 触发条件：当master branch触发push（push，merge Pull Request）时，弱docker文件夹下的文件有更新，则触发。
on:
  push:
    branches:
      - master
    #paths:
     # - 'docker/**'

#defaults:
#  run:
#    shell: bash
#    working-directory: './docker'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      # 将GTIHUB的信息都打印出来，后面的脚本可以使用这些信息，例如后面的镜像TAG用的就是这里面的commitid
        run: echo "Hello ${{ github.event.commits[0].id }}"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag emoji-image:latest
      - name: Push to Ali Docker Repository
        run: |
          echo ${commit_id}
          docker login -u ${{ secrets.ALI_DOCKER_HUB_USN }} -p ${{ secrets.ALI_DOCKER_HUB_PWD }} ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          docker tag emoji-image:latest ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}:${{ github.event.commits[0].id }}
          docker push ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}:${{ github.event.commits[0].id }}
      

